/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5904ede4b1ee23338f0e75dcfa2890dc)
interface __BaseEnv_Env {
	PREVIEW_SECRET: string;
	PAYLOAD_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist-worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
